steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']

  # Generate Prisma Client
  - name: 'node:18'
    entrypoint: npx
    args: ['prisma', 'generate']

  # Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/granada-api', '.']

  # Push container image  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/granada-api']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'granada-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/granada-api'
      - '--region'
      - 'asia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - |
        DATABASE_URL=postgresql://${_DB_USER}:${_DB_PASS}@/${_DB_NAME}?host=/cloudsql/${_INSTANCE_CONNECTION_NAME},
        NODE_ENV=production,
        JWT_ACCESS_SECRET=${_JWT_ACCESS_SECRET},
        JWT_REFRESH_SECRET=${_JWT_REFRESH_SECRET},
        SESSION_SECRET=${_SESSION_SECRET},
        IMAGEKIT_PUBLIC_KEY=${_IMAGEKIT_PUBLIC_KEY},
        IMAGEKIT_PRIVATE_KEY=${_IMAGEKIT_PRIVATE_KEY},
        IMAGEKIT_URL_ENDPOINT=${_IMAGEKIT_URL_ENDPOINT},
        EMAIL_USER=${_EMAIL_USER},
        EMAIL_PASS=${_EMAIL_PASS},
        CORS_ORIGIN=${_CORS_ORIGIN},
        GCS_KEYFILE=${_GCS_KEYFILE},
        GOOGLE_CLOUD_PROJECT_ID=${PROJECT_ID},
        GOOGLE_CLOUD_BUCKET_NAME=${_BUCKET_NAME}
      - '--add-cloudsql-instances'
      - '${_INSTANCE_CONNECTION_NAME}'
      - '--service-account'
      - '${_SERVICE_ACCOUNT}'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '8'

substitutions:
  _DB_USER: postgres
  _DB_NAME: granada_db
  _INSTANCE_CONNECTION_NAME: ${PROJECT_ID}:asia-southeast2:granada-db
  _BUCKET_NAME: granada-storage
  _SERVICE_ACCOUNT: granada-service@${PROJECT_ID}.iam.gserviceaccount.com


images:
  - 'gcr.io/$PROJECT_ID/granada-api'

timeout: '1800s'