steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']

  # Generate Prisma Client
  - name: 'node:18'
    entrypoint: npx
    args: ["prisma", "migrate", "dev"]

  # Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE_NAME', '.']

  # Push container image  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE_NAME']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'granada-api'
    - '--image'
    - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE_NAME'
    - '--region'
    - 'asia-southeast2'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--cpu-boost'
    - '--execution-environment'
    - 'gen2'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--min-instances'
    - '1'
    - '--max-instances'
    - '8'
    - '--timeout'
    - '600s'
    - '--command'
    - 'node'
    - '--args'
    - 'app.js'
    - '--set-cloudsql-instances'
    - 'river-sky-416523:asia-southeast2:pinanda1'
    - '--set-env-vars'
    - |
      DATABASE_URL=DATABASE_URL=DATABASE_URL=postgresql://postgres:${_DB_PASS}@localhost/postgres?host=/cloudsql/river-sky-416523:asia-southeast2:pinanda1,
      NODE_ENV=production,
      JWT_ACCESS_SECRET=${_JWT_ACCESS_SECRET},
      JWT_REFRESH_SECRET=${_JWT_REFRESH_SECRET},
      SESSION_SECRET=${_SESSION_SECRET},
      IMAGEKIT_PUBLIC_KEY=${_IMAGEKIT_PUBLIC_KEY},
      IMAGEKIT_PRIVATE_KEY=${_IMAGEKIT_PRIVATE_KEY},
      IMAGEKIT_URL_ENDPOINT=${_IMAGEKIT_URL_ENDPOINT},
      EMAIL_USER=${_EMAIL_USER},
      EMAIL_PASS=${_EMAIL_PASS},
      CORS_ORIGIN=${_CORS_ORIGIN},
      GOOGLE_CLOUD_PROJECT_ID=${PROJECT_ID},
      GOOGLE_CLOUD_BUCKET_NAME=${_BUCKET_NAME}
    - '--service-account'
    - '${_SERVICE_ACCOUNT}'

images:
  - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE_NAME'