name: Build and Push to GCR
on:
  push:
    branches: [ main ]
  
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE_NAME: granada-api
  REGISTRY_LOCATION: asia-southeast2-docker.pkg.dev
  REPOSITORY: granada-repository
  
jobs:
  build-and-push:
    permissions:
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker asia-southeast2-docker.pkg.dev
    - name: Build Docker image
      run: |
        docker build -t $REGISTRY_LOCATION/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} .
        docker tag $REGISTRY_LOCATION/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} $REGISTRY_LOCATION/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest
    - name: Push Docker image
      run: |
        docker push $REGISTRY_LOCATION/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}
        docker push $REGISTRY_LOCATION/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy granada-api \
          --image=$REGISTRY_LOCATION/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest \
          --region=asia-southeast2 \
          --platform=managed \
          --allow-unauthenticated \
          --timeout=300s \
          --memory=1Gi \
          --cpu=1 \
          --min-instances=1 \
          --max-instances=8 \
          --set-env-vars="NODE_ENV=production" \
          --add-cloudsql-instances=${{ secrets.INSTANCE_CONNECTION_NAME }} \
          --port=8080
