name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authorize Docker push
      run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev

    - name: Build and Push Container
      run: |
        docker build -t asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/granada-repository/granada-api:${{ github.sha }} .
        docker push asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/granada-repository/granada-api:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy granada-api \
          --image=asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/granada-repository/granada-api:${{ github.sha }} \
          --region=asia-southeast2 \
          --platform=managed \
          --port=8080 \
          --memory=1Gi \
          --cpu=1 \
          --min-instances=1 \
          --max-instances=8 \
          --allow-unauthenticated \
          --set-env-vars=NODE_ENV=production \
          --set-env-vars=DATABASE_URL=${{ secrets.DATABASE_URL }} \
          --set-env-vars=JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }} \
          --set-env-vars=JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }} \
          --set-env-vars=SESSION_SECRET=${{ secrets.SESSION_SECRET }} \
          --add-cloudsql-instances=${{ secrets.INSTANCE_CONNECTION_NAME }}