name: Build and Push to GCR

on:
  push:
    branches: [ main ]
  
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE_NAME: granada-api
  REGISTRY_LOCATION: asia-southeast2-docker.pkg.dev
  REPOSITORY: granada-repository
  
jobs:
  build-and-push:
    permissions:
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Generate Prisma Client
      run: npx prisma generate
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      
    - name: Enable necessary APIs
      run: |
        gcloud services enable run.googleapis.com
        gcloud services enable sql-component.googleapis.com
        gcloud services enable sqladmin.googleapis.com
    
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker $REGISTRY_LOCATION --quiet
    
    - name: Build Docker image
      run: |
        docker build -t $REGISTRY_LOCATION/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} .
    
    - name: Push Docker image
      run: |
        docker push $REGISTRY_LOCATION/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy granada-api \
          --image=$REGISTRY_LOCATION/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} \
          --region=asia-southeast2 \
          --platform=managed \
          --allow-unauthenticated \
          --execution-environment=gen2 \
          --timeout=600s \
          --memory=1Gi \
          --cpu=1 \
          --min-instances=1 \
          --max-instances=8 \
          --cpu-boost \
          --port=8080 \
          --startup-cpu-boost \
          --vpc-connector=${PROJECT_ID}-connector \
          --set-env-vars="NODE_ENV=production,DATABASE_URL=${{ secrets.DATABASE_URL }},CORS_ORIGIN=${{ secrets.CORS_ORIGIN }},JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }},JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }},SESSION_SECRET=${{ secrets.SESSION_SECRET }},EMAIL_USER=${{ secrets.EMAIL_USER }},EMAIL_PASS=${{ secrets.EMAIL_PASS }},IMAGEKIT_PUBLIC_KEY=${{ secrets.IMAGEKIT_PUBLIC_KEY }},IMAGEKIT_PRIVATE_KEY=${{ secrets.IMAGEKIT_PRIVATE_KEY }},IMAGEKIT_URL_ENDPOINT=${{ secrets.IMAGEKIT_URL_ENDPOINT }},GOOGLE_CLOUD_PROJECT_ID=${{ secrets.GOOGLE_CLOUD_PROJECT_ID }},GOOGLE_CLOUD_BUCKET_NAME=${{ secrets.GOOGLE_CLOUD_BUCKET_NAME }},GCS_BUCKET_NAME=${{ secrets.GCS_BUCKET_NAME }}" \
          --add-cloudsql-instances=${{ secrets.INSTANCE_CONNECTION_NAME }} \
          --service-account=${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }} \
          --clear-vpc-connector