name: Build and Push to GCR

on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE_NAME: granada-api
  REGISTRY_LOCATION: asia-southeast2-docker.pkg.dev
  REPOSITORY: granada-repository
  
jobs:
  build-and-push:
    permissions:
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate Prisma Client
      run: npx prisma generate
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      
    - name: Check necessary APIs
      run: |
        gcloud services list --enabled --filter="name:run.googleapis.com" || echo "Cloud Run API may not be enabled. Continuing..."
        gcloud services list --enabled --filter="name:sql-component.googleapis.com" || echo "SQL Component API may not be enabled. Continuing..."
        gcloud services list --enabled --filter="name:sqladmin.googleapis.com" || echo "SQL Admin API may not be enabled. Continuing..."
    
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker $REGISTRY_LOCATION --quiet
    
    - name: Build Docker image
      run: |
        docker build -t $REGISTRY_LOCATION/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} .
    
    - name: Push Docker image
      run: |
        docker push $REGISTRY_LOCATION/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy granada-api \
          --image=$REGISTRY_LOCATION/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} \
          --region=asia-southeast2 \
          --platform=managed \
          --allow-unauthenticated \
          --execution-environment=gen2 \
          --timeout=600s \
          --memory=1Gi \
          --cpu=1 \
          --min-instances=1 \
          --max-instances=8 \
          --cpu-boost \
          --set-cloudsql-instances=river-sky-416523:asia-southeast2:pinanda1 \
          --set-env-vars="NODE_ENV=production,DATABASE_URL=postgresql://postgres:${{ secrets.DB_PASSWORD }}@34.128.96.22:5432/Granada_Backend?sslmode=no-verify,CORS_ORIGIN=${{ secrets.CORS_ORIGIN }},JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }},JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }},SESSION_SECRET=${{ secrets.SESSION_SECRET }},EMAIL_USER=${{ secrets.EMAIL_USER }},EMAIL_PASS=${{ secrets.EMAIL_PASS }},IMAGEKIT_PUBLIC_KEY=${{ secrets.IMAGEKIT_PUBLIC_KEY }},IMAGEKIT_PRIVATE_KEY=${{ secrets.IMAGEKIT_PRIVATE_KEY }},IMAGEKIT_URL_ENDPOINT=${{ secrets.IMAGEKIT_URL_ENDPOINT }},GOOGLE_CLOUD_PROJECT_ID=river-sky-416523,GOOGLE_CLOUD_BUCKET_NAME=${{ secrets.GOOGLE_CLOUD_BUCKET_NAME }}"

          
    - name: Log deployment URL
      run: |
        echo "🚀 Deployment complete! Your app is available at:"
        gcloud run services describe granada-api --region=asia-southeast2 --format='value(status.url)'